<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="608984" started-at="2019-11-13T17:31:19Z" finished-at="2019-11-13T17:41:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="608984" started-at="2019-11-13T17:31:19Z" finished-at="2019-11-13T17:41:28Z">
      <class name="com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement">
        <test-method status="PASS" signature="initialSetup()[pri:0, instance:com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement@282ba1e]" name="initialSetup" is-config="true" duration-ms="579" started-at="2019-11-13T23:01:19Z" finished-at="2019-11-13T23:01:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method status="FAIL" signature="SCM_CHILE_CST_011_TransferTransactionsToCSTManagement_TC()[pri:0, instance:com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement@282ba1e]" name="SCM_CHILE_CST_011_TransferTransactionsToCSTManagement_TC" duration-ms="608967" started-at="2019-11-13T23:01:19Z" finished-at="2019-11-13T23:11:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to verify Process submitted message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to verify Process submitted message
	at org.testng.Assert.fail(Assert.java:94)
	at com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement_TC(SCM_CHILE_CST_011_TransferTransactionsToCSTManagement.java:706)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SCM_CHILE_CST_011_TransferTransactionsToCSTManagement_TC -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement@282ba1e]" name="quitBrowser" is-config="true" duration-ms="1159" started-at="2019-11-13T23:11:28Z" finished-at="2019-11-13T23:11:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.testcases.SCM_CHILE_CST_011_TransferTransactionsToCSTManagement -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
