<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PRADHR-IN" name="com.testcases.HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus" tests="1" failures="1" timestamp="6 Nov 2019 15:24:51 GMT" time="330.838" errors="0">
  <testcase name="HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus_TC" time="330.838" classname="com.testcases.HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus">
    <failure type="java.lang.AssertionError" message="Confirmation message has not Popped up">
      <![CDATA[java.lang.AssertionError: Confirmation message has not Popped up
	at org.testng.Assert.fail(Assert.java:94)
	at com.testcases.HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus.HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus_TC(HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus_TC -->
</testsuite> <!-- com.testcases.HCM_CHILE_T003_15_View_Update_PrsnlInfo_UpdateGenderAndMartialStatus -->
